### ISSUE TITLE
iio_scan_context_get_info_list Generating errors when no devices available

### ISSUE THREAD

**Issue by tfcollins** [analogdevicesinc/libiio#794]
This appeared within the last few days.

Running iio_info and python equivalent returns errors on scanning. Example with fresh ubuntu 20.04 docker image:

iio_info
```
root@7ca8be9d8f5f:/work# iio_info -S
Library version: 0.23 (git tag: cad8314)
Compiled with backends: local xml ip usb
Scanning for IIO contexts failed: No such device (19)
```
Python
```
root@7ca8be9d8f5f:/work# python3 -c "import iio; ctxs = iio.scan_contexts()"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python3.8/dist-packages/iio.py", line 1511, in scan_contexts
    ctx_nb = _get_context_info_list(ctx, _byref(ptr))
  File "/usr/local/lib/python3.8/dist-packages/iio.py", line 62, in _check_negative
    raise OSError(-result, _strerror(-result))
```
pyadi build: https://github.com/analogdevicesinc/pyadi-iio/runs/5251654994?check_suite_focus=true#step:5:64195

Bisecting breaking change: https://github.com/analogdevicesinc/libiio/commit/b058c6977d9f132128335586be29104aa9e6e3cc

**Comment by pcercuei** [comment]
@tfcollins I can't reproduce. I built it from the exact same git commit, and it works fine on my ZedBoard (detects the local backend) and on my PC (detects my Pluto).

**Comment by tfcollins** [comment]
Try it without a device or context available

**Comment by pcercuei** [comment]
@tfcollins could you share the generated `iio-config.h` file?

**Comment by tfcollins** [comment]
```
#ifndef IIO_CONFIG_H
#define IIO_CONFIG_H

#define LIBIIO_VERSION_MAJOR	0
#define LIBIIO_VERSION_MINOR	23
#define LIBIIO_VERSION_GIT	"cad8314"

#define LOG_LEVEL Info_L

#define WITH_LOCAL_BACKEND 1
#define WITH_XML_BACKEND 1
#define WITH_NETWORK_BACKEND 1
#define WITH_USB_BACKEND 1
#define WITH_SERIAL_BACKEND 0

/* #undef WITH_NETWORK_GET_BUFFER */
#define WITH_NETWORK_EVENTFD 1
#define WITH_IIOD_USBD 1
#define WITH_IIOD_SERIAL 1
#define WITH_LOCAL_CONFIG 1
#define WITH_LOCAL_MMAP_API 1
#define WITH_HWMON 0
#define WITH_AIO 1
#define HAVE_DNS_SD 0
#define HAVE_AVAHI 0
#define WITH_ZSTD 0

/* #undef HAS_PIPE2 */
#define HAS_STRDUP
#define HAS_STRNDUP
#define HAS_STRTOK_R
#define HAS_STRERROR_R
#define HAS_NEWLOCALE
#define HAS_PTHREAD_SETNAME_NP
#define HAVE_IPV6
/* #undef NO_THREADS */
#define HAS_LIBUSB_GETVERSION

#endif /* IIO_CONFIG_H */
```

**Comment by rgetz** [comment]
yeah, this happens because we tell you to find something on ip, and ip is built without DNS_SD support...

So, this fixes it - I can make a PR if @pcercuei agrees with the fix.

```
diff --git a/scan.c b/scan.c
index 503864e..8030fba 100644
--- a/scan.c
+++ b/scan.c
@@ -155,7 +156,7 @@ struct iio_scan_context * iio_create_scan_context(
                return NULL;
        }
 
-       ctx->backendopts = iio_strndup(backend ? backend : "local,usb,ip", PATH_MAX);
+       ctx->backendopts = iio_strndup(backend ? backend : (HAVE_DNS_SD ? "local,usb,ip" : "local,usb"), PATH_MAX);
        if (!ctx->backendopts) {
                free(ctx);
                errno = ENOMEM;
```

**Comment by pcercuei** [comment]
@rgetz that's not the right fix. If you disable the local or USB backends you will get the same issue.

**Comment by rgetz** [comment]
yeah, this fixes things in a more general purpose way. 

Thanks
